### ISSUE TITLE
default installation instructions

### ISSUE THREAD

**Issue by Theodore-Chatziioannou** [arup-group/cookiecutter-pypackage#18]
### What can be improved?

The default installation instructions for non-developers currently point to the city-modelling-lab conda channel. I think it would should have a local installation as a the default, and and only point to conda if/once the project has been set up there. Or provide an option for either during the repo setup process.

### Version

v0.1.0

**Comment by brynpickering** [comment]
The defaults for `upload_conda_pacakge` and `upload_pypi_package` could be "no" so that you end up by default with the instructions to install from github and _then_ when you're comfortable with uploading to either/both you could update your repository:

```bash
cruft update --variables-to-update '{ "upload_conda_package" : "y" , "upload_pypi_package": "y"}'
```

This would inject the relevant CI and update the install instructions (although likely with `.rej` files that have to be manually resolved).

Would that work?

**Comment by Theodore-Chatziioannou** [comment]
yeah I believe so
